"""202602150-db-changes

Revision ID: 77402a4b3b5c
Revises: 17a2092b4ddf
Create Date: 2026-02-15 05:57:17.598615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77402a4b3b5c'
down_revision: Union[str, Sequence[str], None] = '17a2092b4ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('experience_level', sa.VARCHAR(), nullable=True),
    sa.Column('trading_duration', sa.VARCHAR(), nullable=True),
    sa.Column('risk_tolerance', sa.VARCHAR(), nullable=True),
    sa.Column('capital_allocation', sa.VARCHAR(), nullable=True),
    sa.Column('asset_preference', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    # ### end Alembic commands ###
